name: lucifer
description: A fast, light-weight web framework to provide a simple way to fulfill the needs of many modern web server these days.
version: 1.0.7
homepage: https://github.com/atroxic/lucifer
repo: https://github.com/atroxic/lucifer
fork: https://github.com/salkuadrat/lucifer

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  dotenv: ^4.1.0
  mime: ^1.0.1
  mime_type: ^1.0.0
  queue: ^3.1.0+1
  logger: ^2.0.2
  http_parser: ^4.0.0
  http_status_code: ^0.0.2
  dart_jsonwebtoken: ^2.11.0
  mustache_template: ^2.0.0
  sanitize_html: ^2.0.0
  cryptography: ^2.0.5
  uuid: ^4.0.0

dev_dependencies:
  lints: ^2.1.1
  test: ^1.16.0
  http: ^1.1.0